# Generated by Django 2.1.3 on 2018-11-13 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('dscr', models.CharField(max_length=128)),
                ('image', models.FileField(upload_to='')),
                ('checked', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('dscr', models.CharField(max_length=128)),
                ('image', models.FileField(upload_to='')),
                ('num_child_groups', models.IntegerField()),
                ('num_child_elements', models.IntegerField()),
                ('parent_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_api.Groups')),
            ],
        ),
        migrations.AddField(
            model_name='elements',
            name='parent_group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_api.Groups'),
        ),
    ]
