# Generated by Django 2.1.3 on 2018-11-13 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0002_auto_20181113_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='date_of_creation',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
