# Generated by Django 2.1.3 on 2018-11-13 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0003_element_date_of_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='parent_group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_api.Group'),
        ),
    ]
