# Generated by Django 2.1.3 on 2018-11-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0005_auto_20181113_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='checked',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='group',
            name='num_child_elements',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='group',
            name='num_child_groups',
            field=models.IntegerField(default=0),
        ),
    ]
