# Generated by Django 2.1.3 on 2018-11-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0006_auto_20181116_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='test_field',
            field=models.IntegerField(default=0),
        ),
    ]
