# Generated by Django 2.1.3 on 2018-11-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0009_auto_20181117_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='checked',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
