# Generated by Django 2.1.3 on 2018-11-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0010_auto_20181117_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='parent_group_id',
            new_name='parent_group',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='parent_group_id',
            new_name='parent_group',
        ),
        migrations.AlterField(
            model_name='element',
            name='dscr',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='dscr',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='num_child_elements',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='num_child_groups',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
